name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [dev]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  pages:
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: ./docs/source
        requirements_path: requirements.txt
        pyproject_extras: dev
        python_version: 3.10
