name: Tests

on:
  push:
    branches:
      - '**'
      - '!gh-pages'
  pull_request:
    branches:
      - '**'
      - '!gh-pages'
  workflow_dispatch:

jobs:
  tox-tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Test with tox
      run: tox -e py$(echo ${{ matrix.python-version }} | tr -d '.')
      env:
        PLATFORM: ${{ matrix.os }}
